=== fermadeiral/bears-benchmark/core/src/main/resources/com/aspectran/core/context/rule/parser/xml/dtd/aspectran-5.dtd
<?xml version="1.0" encoding="utf-8"?>

<!--
  XML DTD for the Aspectran Configuration File, Version 5.0

  Copyright 2008-2017 The Aspectran Project

  This DTD module is identified by the PUBLIC and SYSTEM identifiers:

  PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
  SYSTEM "http://aspectran.github.io/dtd/aspectran-5.dtd">

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                             "http://aspectran.github.io/dtd/aspectran-5.dtd">
-->

<!ELEMENT aspectran (
  description?,
  (settings? | environment* | typeAliases* | aspect* | bean* | template* | schedule* | translet* | append*)*
)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  style   (apon | compact | compressed) #IMPLIED
>

<!ELEMENT settings (#PCDATA | setting)*>
<!ELEMENT setting (#PCDATA)>
<!ATTLIST setting
  name    CDATA #REQUIRED
  value   CDATA #IMPLIED
>

<!ELEMENT environment (#PCDATA | properties)*>
<!ATTLIST environment
  profile CDATA #IMPLIED
>

<!ELEMENT typeAliases (typeAlias*)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
  alias   CDATA #REQUIRED
  type    CDATA #REQUIRED
>

<!ELEMENT append EMPTY>
<!ATTLIST append
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  format   (xml | apon) #IMPLIED
  profile  CDATA #IMPLIED
>

<!ELEMENT aspect (description?, joinpoint?, settings?, advice?, exception?)>
<!ATTLIST aspect
  id       ID #IMPLIED
  order    CDATA #IMPLIED
  isolated (true | false) #IMPLIED
>

<!ELEMENT joinpoint (#PCDATA)>
<!ATTLIST joinpoint
  target  (session | translet | method) #IMPLIED
>

<!ELEMENT advice (before?, after?, around?, finally?)>
<!ATTLIST advice
  bean    CDATA #IMPLIED
>

<!ELEMENT before  (headers | echo | action)>
<!ELEMENT after   (headers | echo | action)>
<!ELEMENT around  (action)>
<!ELEMENT finally (thrown?, (headers | echo | action))>

<!ELEMENT exception (description?, thrown*)>

<!ELEMENT thrown ((headers | echo | action)? | transform? | dispatch? | redirect? | forward?)*>
<!ATTLIST thrown
  type    CDATA #IMPLIED
>

<!ELEMENT bean (description?, filter?, constructor?, properties?)>
<!ATTLIST bean
  id            CDATA #IMPLIED
  class         CDATA #IMPLIED
  scan          CDATA #IMPLIED
  mask          CDATA #IMPLIED
  factoryBean   CDATA #IMPLIED
  factoryMethod CDATA #IMPLIED
  initMethod    CDATA #IMPLIED
  destroyMethod CDATA #IMPLIED
  scope         (singleton | prototype | request | session | application) #IMPLIED
  singleton     (true | false) #IMPLIED
  lazyInit      (true | false) #IMPLIED
  important     (true | false) #IMPLIED
>

<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
  class   CDATA #IMPLIED
>

<!ELEMENT constructor (arguments?)>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template
  id       CDATA #IMPLIED
  engine   CDATA #IMPLIED
  style    (apon | compact | compressed) #IMPLIED
  name     CDATA #IMPLIED
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  encoding CDATA #IMPLIED
  noCache  (true | false) #IMPLIED
>

<!ELEMENT schedule (description?, scheduler, job*)>
<!ATTLIST schedule
  id      ID #IMPLIED
>

<!ELEMENT scheduler (trigger)>
<!ATTLIST scheduler
  bean    CDATA #IMPLIED
>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
  type    CDATA #IMPLIED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
  translet CDATA #REQUIRED
  method   CDATA #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT translet (
  (description?, request?, content*, contents?, response*, exception?) |
  (description?, request?, content*, contents?, (transform | dispatch | redirect | forward)?, exception?) |
  (description?, request?, (action? | include? | echo? | headers?)*, response*, exception?) |
  (description?, request?, (action? | include? | echo? | headers?)*, (transform | dispatch | redirect | forward)?, exception?) |
  (description?, parameters?, attributes?, (action? | include? | echo? | headers?)*, (transform | dispatch | redirect | forward)?, exception?)
)>
<!ATTLIST translet
  name    CDATA #REQUIRED
  scan    CDATA #IMPLIED
  mask    CDATA #IMPLIED
  method  CDATA #IMPLIED
>

<!ELEMENT request (parameters?, attributes?)>
<!ATTLIST request
  method   CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT contents (content*)>
<!ATTLIST contents
  name      CDATA #IMPLIED
  omittable (true | false) #IMPLIED
>

<!ELEMENT content (action? | include? | echo? | headers?)*>
<!ATTLIST content
  name      CDATA #IMPLIED
  omittable (true | false) #IMPLIED
  hidden    (true | false) #IMPLIED
>

<!ELEMENT action (arguments?, properties?)>
<!ATTLIST action
  id      CDATA #IMPLIED
  bean    CDATA #IMPLIED
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT include (parameters?, attributes?)>
<!ATTLIST include
  id       CDATA #IMPLIED
  translet CDATA #REQUIRED
  hidden   (true | false) #IMPLIED
>

<!ELEMENT echo (#PCDATA | attributes | item)*>
<!ATTLIST echo
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT headers (#PCDATA | item)*>
<!ATTLIST headers
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT response (transform? | dispatch? | redirect? | forward?)>
<!ATTLIST response
  name     CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT transform ((action? | include? | echo? | headers?)*, (template? | call?))>
<!ATTLIST transform
  type        CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
  pretty      (true | false) #IMPLIED
>

<!ELEMENT dispatch (action? | include? | echo? | headers?)*>
<!ATTLIST dispatch
  name        CDATA #REQUIRED
  dispatcher  CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT redirect ((action? | include? | echo? | headers?)*, parameters*)>
<!ATTLIST redirect
  contentType           CDATA #IMPLIED
  path                  CDATA #REQUIRED
  encoding              CDATA #IMPLIED
  excludeNullParameter  (true | false) #IMPLIED
  excludeEmptyParameter (true | false) #IMPLIED
  default               (true | false) #IMPLIED
>

<!ELEMENT forward ((action? | include? | echo? | headers?)*, attributes?)>
<!ATTLIST forward
  contentType CDATA #IMPLIED
  translet    CDATA #REQUIRED
  default     (true | false) #IMPLIED
>

<!ELEMENT parameters (#PCDATA | item)*>
<!ELEMENT attributes (#PCDATA | item)*>
<!ELEMENT properties (#PCDATA | item)*>
<!ELEMENT arguments  (#PCDATA | item)*>

<!ELEMENT item (#PCDATA | value | call | null)*>
<!ATTLIST item
  type         (single | array | list | map | set | properties) #IMPLIED
  name         CDATA #IMPLIED
  value        CDATA #IMPLIED
  valueType    (string | int | long | float | double | boolean | parameters | file | multipartFile) #IMPLIED
  defaultValue CDATA #IMPLIED
  tokenize     (true | false) #IMPLIED
  mandatory    (true | false) #IMPLIED
  security     (true | false) #IMPLIED
>

<!ELEMENT value (#PCDATA | call | null)*>
<!ATTLIST value
  name     CDATA #IMPLIED
  tokenize (true | false) #IMPLIED
>

<!ELEMENT call EMPTY>
<!ATTLIST call
  bean      CDATA #IMPLIED
  template  CDATA #IMPLIED
  parameter CDATA #IMPLIED
  attribute CDATA #IMPLIED
  property  CDATA #IMPLIED
>

<!ELEMENT null EMPTY>

=== fermadeiral/bears-benchmark/demo/app/config/aspectran/web/translets/gs-rest-service.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        A collection of Translets for the Restful Web Service example.
    </description>

    <settings>
        <setting name="transletNamePattern" value="/examples/gs-rest-service/*"/>
    </settings>

    <bean class="com.aspectran.demo.customer.CustomerDao"/>

    <bean class="com.aspectran.demo.customer.CustomerAction"/>

    <translet name="/">
        <dispatch name="templates/default">
            <echo id="page">
                <attributes>
                    <item name="headline">Building a RESTful Web Service</item>
                    <item name="teaser">A sample page that uses RESTful web services using HTTP support methods such as GET, PUT, POST, and DELETE.</item>
                    <item name="include">pages/gs-rest-service</item>
                </attributes>
            </echo>
        </dispatch>
    </translet>

    <translet name="customers" method="GET">
        <description>
            전체 고객 목록을 조회합니다.
        </description>
        <action id="customers" bean="class:com.aspectran.demo.customer.CustomerAction" method="getCustomerList"/>
        <transform type="transform/json" pretty="true"/>
    </translet>

    <translet name="customers/${id:guest}" method="GET">
        <description>
            id를 파라메터로 받아서 해당 id를 가진 고객의 상세정보를 조회합니다.
            고객번호를 지정하지 않으면 고객번호가 "guest"인 고객의 상세정보를 조회합니다.
        </description>
        <action id="customer" bean="class:com.aspectran.demo.customer.CustomerAction" method="getCustomer"/>
        <transform type="transform/json" pretty="true"/>
    </translet>

    <translet name="customers" method="POST">
        <description>
            고객정보를 등록합니다.
        </description>
        <action bean="class:com.aspectran.demo.customer.CustomerAction" method="insertCustomer"/>
        <transform type="transform/json" pretty="true"/>
    </translet>

    <translet name="customers/${id}" method="PUT">
        <description>
            고객정보를 수정합니다.
        </description>
        <action bean="class:com.aspectran.demo.customer.CustomerAction" method="updateCustomer"/>
        <transform type="transform/json" pretty="true"/>
    </translet>

    <translet name="customers/${id}/approve/${approved}" method="PUT">
        <description>
            id를 파라메터로 받아서 해당 id를 가진 고객에 대해 승인처리를 합니다.
            "${approved}"는 승인여부에 해당하는 값을 지정합니다. (true or false)
        </description>
        <action id="result" bean="class:com.aspectran.demo.customer.CustomerAction" method="approve"/>
        <transform type="transform/json" pretty="true"/>
    </translet>

    <translet name="customers/${id}/approve" method="GET">
        <description>
            id를 파라메터로 받아서 해당 id를 가진 고객에 대하여 승인여부를 조회합니다.
        </description>
        <action id="result" bean="class:com.aspectran.demo.customer.CustomerAction" method="isApproved"/>
        <transform type="transform/json" pretty="true"/>
    </translet>

    <translet name="customers/${id}" method="DELETE">
        <description>
            id를 파라메터로 받아서 해당 id를 가진 고객의 정보를 삭제합니다.
        </description>
        <action id="result" bean="class:com.aspectran.demo.customer.CustomerAction" method="deleteCustomer"/>
        <transform type="transform/json" pretty="true"/>
    </translet>

</aspectran>

=== fermadeiral/bears-benchmark/embed/src/test/resources/config/aop/simple-aop-test-config.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        Aspectran's AOP is simple and powerful.
    </description>

    <bean scan="com.aspectran.aop.*Action"/>

    <bean scan="com.aspectran.aop.*Aspect"/>

    <bean id="simpleAopTestAdvice" class="com.aspectran.aop.SimpleAopTestAdvice"/>

    <aspect id="aspect01" order="1">
        <joinpoint target="translet">
            pointcut: {
                +: aop/test/*
            }
        </joinpoint>
        <advice bean="simpleAopTestAdvice">
            <before>
                <action method="begin"/>
            </before>
            <after>
                <action method="end"/>
            </after>
            <finally>
                <thrown>
                    <action method="thrown"/>
                </thrown>
                <action method="close"/>
            </finally>
        </advice>
        <exception>
            <thrown>
                <action bean="simpleAopTestAdvice" method="globalExceptionHandling"/>
            </thrown>
        </exception>
    </aspect>

</aspectran>

=== fermadeiral/bears-benchmark/embed/src/test/resources/config/scheduler/scheduler-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <settings>
        <setting name="transletNamePattern" value="*.job"/>
    </settings>

    <bean id="*" scan="com.aspectran.embed.**.*Advice" mask="com.aspectran.embed.**.*"/>
    <bean id="*" scan="com.aspectran.embed.**.*Action" mask="com.aspectran.embed.**.*"/>

    <bean id="defaultScheduler1" class="com.aspectran.scheduler.support.QuartzSchedulerFactoryBean" lazyInit="true">
        <properties>
            <item type="properties" name="quartzProperties">
                <value name="org.quartz.scheduler.instanceName">AspectranQuartzScheduler-1</value>
                <value name="org.quartz.scheduler.rmi.export">false</value>
                <value name="org.quartz.scheduler.rmi.proxy">false</value>
                <value name="org.quartz.scheduler.wrapJobExecutionInUserTransaction">false</value>
                <value name="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</value>
                <value name="org.quartz.threadPool.threadCount">10</value>
                <value name="org.quartz.threadPool.threadPriority">5</value>
                <value name="org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread">true</value>
                <value name="org.quartz.jobStore.misfireThreshold">60001</value>
                <value name="org.quartz.jobStore.class">org.quartz.simpl.RAMJobStore</value>
            </item>
        </properties>
    </bean>

    <bean id="schedulerFactory" class="org.quartz.impl.StdSchedulerFactory" lazyInit="true">
        <constructor>
            <arguments>
                <item type="properties">
                    <value name="org.quartz.scheduler.instanceName">AspectranQuartzScheduler-2</value>
                    <value name="org.quartz.scheduler.rmi.export">false</value>
                    <value name="org.quartz.scheduler.rmi.proxy">false</value>
                    <value name="org.quartz.scheduler.wrapJobExecutionInUserTransaction">false</value>
                    <value name="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</value>
                    <value name="org.quartz.threadPool.threadCount">10</value>
                    <value name="org.quartz.threadPool.threadPriority">5</value>
                    <value name="org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread">true</value>
                    <value name="org.quartz.jobStore.misfireThreshold">60000</value>
                    <value name="org.quartz.jobStore.class">org.quartz.simpl.RAMJobStore</value>
                </item>
            </arguments>
        </constructor>
    </bean>

    <bean id="defaultScheduler2" factoryBean="schedulerFactory" factoryMethod="getScheduler" lazyInit="true"/>

    <schedule id="scheduler1">
        <scheduler bean="defaultScheduler1">
            <trigger type="simple">
                intervalInSeconds: 3
                repeatCount: 10
            </trigger>
        </scheduler>
        <job translet="job1"/>
    </schedule>

    <schedule id="scheduler2">
        <scheduler bean="defaultScheduler2">
            <trigger type="simple">
                startDelaySeconds: 2
                intervalInSeconds: 1
                repeatCount: 10
            </trigger>
        </scheduler>
        <job translet="job2"/>
    </schedule>

    <translet name="job1">
        <action bean="sample.schedule.ScheduleAction" method="delay">
            <arguments>
                <item valueType="long">1</item>
            </arguments>
        </action>
        <transform type="transform/text" contentType="text/plain">
            <template>(1) Hello, World!</template>
        </transform>
    </translet>

    <translet name="job2">
        <action bean="sample.schedule.ScheduleAction" method="delay">
            <arguments>
                <item valueType="long">2</item>
            </arguments>
        </action>
        <transform type="transform/text" contentType="text/plain">
            <template>(2) Hello, World!</template>
        </transform>
    </translet>

</aspectran>

=== fermadeiral/bears-benchmark/demo/app/config/aspectran/shell/translets/hello.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        An Aspectran configuration for printing "Hello, World!".
    </description>

    <bean id="helloAction" class="com.aspectran.demo.hello.HelloAction">
        <description>
            Defines a Hello Action Bean that contains the helloWorld() method.
        </description>
    </bean>

    <bean id="helloAdvice" class="com.aspectran.demo.hello.HelloAdvice">
        <description>
            Defines the Advice Bean that has the Advice Method to be injected before and after the Action Method.
        </description>
    </bean>

    <aspect id="helloAdviceAspect">
        <description>
            If a translet that executes the helloWorld method of the helloAction bean is found,
            executes the welcome() method of the helloAdvice bean before executing the translet,
            and executes the goodbye() method of the helloAdvice bean after executing the translet.
        </description>
        <joinpoint target="translet">
            pointcut: {
                +: hello*@helloAction^helloWorld
            }
        </joinpoint>
        <advice bean="helloAdvice">
            <before>
                <action method="welcome"/>
            </before>
            <after>
                <action method="goodbye"/>
            </after>
        </advice>
    </aspect>

    <translet name="hello">
        <description style="apon">
            |
            |   Runs the helloAction.helloWorld() method and prints the returned value to the console.
            |   Maybe the words "Hello, World!" will be printed on the console.
            |   Is it difficult to find the words "Hello, World!" printed on the console?
            |   If so, try running the "hello2" command.
            |
        </description>
        <transform type="transform/text">
            <action id="helloWorld" bean="helloAction" method="helloWorld"/>
        </transform>
    </translet>

    <translet name="hello2">
        <description style="apon">
            |
            |   Runs the helloAction.helloWorld() method and prints the returned value to the
            |   console using ANSI coloring.
            |   Maybe the word "Hello, World!" will be printed on the console with proper margin.
            |
        </description>
        <action id="helloWorld" bean="helloAction" method="helloWorld"/>
        <transform type="transform/text">
            <template style="apon">
                |
                |   {{bg:green}}                         {{off}}
                |   {{bg:green}}   {{magenta,bg:white}}                   {{bg:blue}}   {{off}}
                |   {{bg:green}}   {{magenta,bg:white}}   @{helloWorld}   {{bg:blue}}   {{off}}
                |   {{bg:green}}   {{magenta,bg:white}}                   {{bg:blue}}   {{off}}
                |   {{magenta,bg:blue}}                         {{off}}
                |
            </template>
        </transform>
    </translet>

    <template id="hello" style="apon">
        |Hello, ${what}!
    </template>

</aspectran>

=== fermadeiral/bears-benchmark/core/src/test/resources/config/bean/test-properties.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <bean id="properties" class="java.util.HashMap">
        <constructor>
            <arguments>
                <item type="map">
                    <value name="property1">This is a Property-1</value>
                    <value name="property2">This is a Property-2</value>
                    <value name="property3">This is a Property-3</value>
                </item>
            </arguments>
        </constructor>
    </bean>

	<environment profile="dev">
        <properties>
            <item name="env.property1">DEV-#{properties^property1}</item>
            <item name="env.property2">DEV-#{properties^property2}</item>
            <item name="env.property3">DEV-#{properties^property3}</item>
            <item name="env.property4">DEV-#{properties^property1} / #{properties^property2} / #{properties^property3}</item>
        </properties>
	</environment>

	<environment profile="prod">
        <properties>
            <item name="env.property1">PROD-#{properties^property1}</item>
            <item name="env.property2">PROD-#{properties^property2}</item>
            <item name="env.property3">PROD-#{properties^property3}</item>
            <item name="env.property4">PROD-#{properties^property1} / #{properties^property2} / #{properties^property3}</item>
        </properties>
	</environment>

    <template id="property-1" style="apon">
        |%{env.property1}
    </template>

    <template id="property-2" style="apon">
        |%{env.property2}
    </template>

    <template id="property-3" style="apon">
        |%{env.property3}
    </template>

    <template id="property-4" style="apon">
        |%{env.property4}
    </template>

</aspectran>

=== fermadeiral/bears-benchmark/demo/app/config/aspectran/shell/translets/echo.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        An Aspectran configuration for printing request parameters and attributes directly to the console.
    </description>

    <translet name="echo">
        <description style="apon">
            |
            |   It accepts parameters and print them to the console.
            |
        </description>
        <parameters>
            <item name="input-1" mandatory="false">${prefix} - 1</item>
            <item name="input-2" mandatory="true">${prefix} - 2</item>
            <item name="input-3">${prefix} - 3</item>
        </parameters>
        <transform type="transform/text" contentType="text/plain">
            <template engine="token" style="apon">
                |----------------------------------------------------------
                |The parameters you entered are:
                |   input-1: ${input-1}
                |   input-2: ${input-2}
                |   input-3: ${input-3}
                |----------------------------------------------------------
                |Retrieve from the Activity data map:
                |   input-1: @{data^input-1}
                |   input-2: @{data^input-2}
                |   input-3: @{data^input-3}
                |----------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="echo2">
        <description style="apon">
            |
            |   It accepts parameters and print them to the console.
            |
        </description>
        <parameters>
            <item name="input-1">PARA ${input-1:12345}</item>
            <item name="input-2">PARA ${input-2:67890}</item>
            <item name="input-3">PARA ${input-3-1} and ${input-3-2}</item>
        </parameters>
        <attributes>
            <item name="input-4">ATTR ${input-4}</item>
        </attributes>
        <transform type="transform/text" contentType="text/plain">
            <template engine="token" style="apon">
                |----------------------------------------------------------
                |The input parameters and attributes are as follows:
                |   input-1: ${input-1} - This is a parameter.
                |   input-2: ${input-2} - This is a parameter.
                |   input-3: ${input-3} - This is a parameter.
                |   input-4: @{input-4} - This is an attribute.
                |----------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="login">
        <description style="apon">
            |
            |   It accepts parameters used for login and print them to the console.
            |
        </description>
        <parameters>
            <item name="id" mandatory="true"/>
            <item name="email" mandatory="true">${id}@${domain}</item>
            <item name="password" security="true" defaultValue="(none)"/>
        </parameters>
        <attributes>
            <item name="attr1" mandatory="true">${id}@${domain}</item>
            <item name="attr2" mandatory="true" security="true">${password}</item>
        </attributes>
        <transform type="transform/text">
            <template style="apon">
                |-------------------------------------------------------------------------
                |You have entered the following parameters for login:
                |   email: ${email}
                |   password: ${password}
                |The attributes you entered are:
                |   attr1: @{attr1}
                |   attr2: @{attr2}
                |-------------------------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="chpw">
        <description style="apon">
            |
            |   It accepts parameters for changing the password and print them to the console.
            |
        </description>
        <parameters>
            <item name="email">${emailId}@${emailDomain}</item>
            <item name="password" security="true"/>
            <item name="confirmPassword" security="true"/>
        </parameters>
        <transform type="transform/text">
            <template style="apon">
                |------------------------------------------------------------------------------------
                |You have entered the following parameters for changing the password:
                |   email: ${email}
                |   password: ${password}
                |   confirm password: ${confirmPassword}
                |------------------------------------------------------------------------------------
            </template>
        </transform>
    </translet>

    <bean id="sampleResources" class="com.aspectran.demo.examples.SampleResources"/>

    <translet name="getSampleResourceFile">
        <transform type="transform/text">
            <action id="sampleResourceFile" bean="sampleResources" method="getSampleResourceFile"/>
        </transform>
    </translet>

    <translet name="printSampleResource">
        <transform type="transform/text">
            <template resource="sample_resource.txt"/>
        </transform>
    </translet>

</aspectran>

=== fermadeiral/bears-benchmark/demo/app/config/aspectran/web/terminal/translet-interpreter.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        You can run translets with a command line interpreter implemented using the jQuery Terminal Emulator.
    </description>

    <settings>
        <setting name="transletNamePattern" value="/terminal/*"/>
    </settings>

    <bean id="transletInterpreter" class="com.aspectran.demo.terminal.TransletInterpreter"/>

    <translet name="/">
        <dispatch name="templates/default">
            <echo id="page">
                <attributes>
                    <item name="headline">Translet Interpreter</item>
                    <item name="teaser">You can run translets with a command line interpreter implemented using the jQuery Terminal Emulator.</item>
                    <item name="include">terminal/translet-interpreter</item>
                </attributes>
            </echo>
        </dispatch>
    </translet>

    <append file="/config/aspectran/web/terminal/terminal-commands.xml"/>

</aspectran>
