=== fermadeiral/bears-benchmark/core/src/main/resources/com/aspectran/core/context/rule/parser/xml/dtd/aspectran-5.dtd
<?xml version="1.0" encoding="utf-8"?>

<!--
  XML DTD for the Aspectran Configuration File, Version 5.0

  Copyright 2008-2017 The Aspectran Project

  This DTD module is identified by the PUBLIC and SYSTEM identifiers:

  PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
  SYSTEM "http://aspectran.github.io/dtd/aspectran-5.dtd">

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                             "http://aspectran.github.io/dtd/aspectran-5.dtd">
-->

<!ELEMENT aspectran (
  description?,
  (settings? | environment* | typeAliases* | aspect* | bean* | template* | schedule* | translet* | append*)*
)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  style   (apon | compact | compressed) #IMPLIED
>

<!ELEMENT settings (#PCDATA | setting)*>
<!ELEMENT setting (#PCDATA)>
<!ATTLIST setting
  name    CDATA #REQUIRED
  value   CDATA #IMPLIED
>

<!ELEMENT environment (#PCDATA | properties)*>
<!ATTLIST environment
  profile CDATA #IMPLIED
>

<!ELEMENT typeAliases (typeAlias*)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
  alias   CDATA #REQUIRED
  type    CDATA #REQUIRED
>

<!ELEMENT append EMPTY>
<!ATTLIST append
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  format   (xml | apon) #IMPLIED
  profile  CDATA #IMPLIED
>

<!ELEMENT aspect (description?, joinpoint?, settings?, advice?, exception?)>
<!ATTLIST aspect
  id       ID #IMPLIED
  order    CDATA #IMPLIED
  isolated (true | false) #IMPLIED
>

<!ELEMENT joinpoint (#PCDATA)>
<!ATTLIST joinpoint
  target  (session | translet | method) #IMPLIED
>

<!ELEMENT advice (before?, after?, around?, finally?)>
<!ATTLIST advice
  bean    CDATA #IMPLIED
>

<!ELEMENT before  (headers | echo | action)>
<!ELEMENT after   (headers | echo | action)>
<!ELEMENT around  (action)>
<!ELEMENT finally (thrown?, (headers | echo | action))>

<!ELEMENT exception (description?, thrown*)>

<!ELEMENT thrown ((headers | echo | action)? | transform? | dispatch? | redirect? | forward?)*>
<!ATTLIST thrown
  type    CDATA #IMPLIED
>

<!ELEMENT bean (description?, filter?, constructor?, properties?)>
<!ATTLIST bean
  id            CDATA #IMPLIED
  class         CDATA #IMPLIED
  scan          CDATA #IMPLIED
  mask          CDATA #IMPLIED
  factoryBean   CDATA #IMPLIED
  factoryMethod CDATA #IMPLIED
  initMethod    CDATA #IMPLIED
  destroyMethod CDATA #IMPLIED
  scope         (singleton | prototype | request | session | application) #IMPLIED
  singleton     (true | false) #IMPLIED
  lazyInit      (true | false) #IMPLIED
  important     (true | false) #IMPLIED
>

<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
  class   CDATA #IMPLIED
>

<!ELEMENT constructor (arguments?)>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template
  id       CDATA #IMPLIED
  engine   CDATA #IMPLIED
  style    (apon | compact | compressed) #IMPLIED
  name     CDATA #IMPLIED
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  encoding CDATA #IMPLIED
  noCache  (true | false) #IMPLIED
>

<!ELEMENT schedule (description?, scheduler, job*)>
<!ATTLIST schedule
  id      ID #IMPLIED
>

<!ELEMENT scheduler (trigger)>
<!ATTLIST scheduler
  bean    CDATA #IMPLIED
>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
  type    CDATA #IMPLIED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
  translet CDATA #REQUIRED
  method   CDATA #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT translet (
  (description?, request?, content*, contents?, response*, exception?) |
  (description?, request?, content*, contents?, (transform | dispatch | redirect | forward)?, exception?) |
  (description?, request?, (action? | include? | echo? | headers?)*, response*, exception?) |
  (description?, request?, (action? | include? | echo? | headers?)*, (transform | dispatch | redirect | forward)?, exception?) |
  (description?, parameters?, attributes?, (action? | include? | echo? | headers?)*, (transform | dispatch | redirect | forward)?, exception?)
)>
<!ATTLIST translet
  name    CDATA #REQUIRED
  scan    CDATA #IMPLIED
  mask    CDATA #IMPLIED
  method  CDATA #IMPLIED
>

<!ELEMENT request (parameters?, attributes?)>
<!ATTLIST request
  method   CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT contents (content*)>
<!ATTLIST contents
  name      CDATA #IMPLIED
  omittable (true | false) #IMPLIED
>

<!ELEMENT content (action? | include? | echo? | headers?)*>
<!ATTLIST content
  name      CDATA #IMPLIED
  omittable (true | false) #IMPLIED
  hidden    (true | false) #IMPLIED
>

<!ELEMENT action (arguments?, properties?)>
<!ATTLIST action
  id      CDATA #IMPLIED
  bean    CDATA #IMPLIED
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT include (parameters?, attributes?)>
<!ATTLIST include
  id       CDATA #IMPLIED
  translet CDATA #REQUIRED
  hidden   (true | false) #IMPLIED
>

<!ELEMENT echo (#PCDATA | attributes | item)*>
<!ATTLIST echo
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT headers (#PCDATA | item)*>
<!ATTLIST headers
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT response (transform? | dispatch? | redirect? | forward?)>
<!ATTLIST response
  name     CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT transform ((action? | include? | echo? | headers?)*, (template? | call?))>
<!ATTLIST transform
  type        CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
  pretty      (true | false) #IMPLIED
>

<!ELEMENT dispatch (action? | include? | echo? | headers?)*>
<!ATTLIST dispatch
  name        CDATA #REQUIRED
  dispatcher  CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT redirect ((action? | include? | echo? | headers?)*, parameters*)>
<!ATTLIST redirect
  contentType           CDATA #IMPLIED
  path                  CDATA #REQUIRED
  encoding              CDATA #IMPLIED
  excludeNullParameter  (true | false) #IMPLIED
  excludeEmptyParameter (true | false) #IMPLIED
  default               (true | false) #IMPLIED
>

<!ELEMENT forward ((action? | include? | echo? | headers?)*, attributes?)>
<!ATTLIST forward
  contentType CDATA #IMPLIED
  translet    CDATA #REQUIRED
  default     (true | false) #IMPLIED
>

<!ELEMENT parameters (#PCDATA | item)*>
<!ELEMENT attributes (#PCDATA | item)*>
<!ELEMENT properties (#PCDATA | item)*>
<!ELEMENT arguments  (#PCDATA | item)*>

<!ELEMENT item (#PCDATA | value | call | null)*>
<!ATTLIST item
  type         (single | array | list | map | set | properties) #IMPLIED
  name         CDATA #IMPLIED
  value        CDATA #IMPLIED
  valueType    (string | int | long | float | double | boolean | parameters | file | multipartFile) #IMPLIED
  defaultValue CDATA #IMPLIED
  tokenize     (true | false) #IMPLIED
  mandatory    (true | false) #IMPLIED
  security     (true | false) #IMPLIED
>

<!ELEMENT value (#PCDATA | call | null)*>
<!ATTLIST value
  name     CDATA #IMPLIED
  tokenize (true | false) #IMPLIED
>

<!ELEMENT call EMPTY>
<!ATTLIST call
  bean      CDATA #IMPLIED
  template  CDATA #IMPLIED
  parameter CDATA #IMPLIED
  attribute CDATA #IMPLIED
  property  CDATA #IMPLIED
>

<!ELEMENT null EMPTY>

=== fermadeiral/bears-benchmark/demo/app/config/aspectran/web/terminal/terminal-commands.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <translet name="/hello">
        <request>
            <parameters>
                <item name="email" mandatory="true">${id}@${domain}</item>
                <item name="password" mandatory="true" security="true"/>
            </parameters>
            <attributes>
                <item name="attr1" mandatory="true">${id}@${domain}</item>
                <item name="attr2" mandatory="true" security="true">${password}</item>
                <item name="attr3" mandatory="true"/>
                <item name="attr4" mandatory="true"/>
            </attributes>
        </request>
        <transform type="transform/text">
            <template style="apon">
                |------------------------------------------------
                |The parameters you entered are:
                |   email: ${email}
                |   password: ${password}
                |The attributes you entered are:
                |   attr1: @{attr1}
                |   attr2: @{attr2}
                |   attr3: @{attr3}
                |   attr4: @{attr4}
                |------------------------------------------------
            </template>
        </transform>
    </translet>

</aspectran>

=== fermadeiral/bears-benchmark/with-jetty/src/test/resources/config/aspectran/jetty-config.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        An Aspectran configuration for running Jetty Server.
    </description>

    <environment>
        <properties>
            <item name="jetty.startup" value="false" valueType="boolean"/>
            <item name="jetty.server.port" value="8099" valueType="int"/>
            <item name="jetty.server.minThreads" value="1" valueType="int"/>
            <item name="jetty.server.maxThreads" value="5" valueType="int"/>
        </properties>
    </environment>

    <bean id="jetty.server" class="com.aspectran.with.jetty.JettyServer" lazyInit="true">
        <constructor>
            <arguments>
                <item name="threadPool">
                    <call bean="jetty.threadPool"/>
                </item>
            </arguments>
        </constructor>
        <properties>
            <item name="autoStart" value="%{jetty.startup}"/>
            <item name="connectors" type="array">
                <value><call bean="jetty.connector"/></value>
            </item>
            <item name="handler">
                <call bean="jetty.handler"/>
            </item>
        </properties>
    </bean>

    <bean id="jetty.threadPool" class="org.eclipse.jetty.util.thread.QueuedThreadPool" scope="prototype">
        <properties>
            <item name="minThreads" value="%{jetty.server.minThreads}"/>
            <item name="maxThreads" value="%{jetty.server.maxThreads}"/>
        </properties>
    </bean>

    <bean id="jetty.connector" class="org.eclipse.jetty.server.ServerConnector" scope="prototype">
        <constructor>
            <arguments>
                <item><call bean="jetty.server"/></item>
            </arguments>
        </constructor>
        <properties>
            <item name="port" value="%{jetty.server.port}"/>
        </properties>
    </bean>

    <bean id="jetty.handler" class="org.eclipse.jetty.server.handler.HandlerCollection" scope="prototype">
        <properties>
            <item name="handlers" type="array">
                <value><call bean="jetty.contexts"/></value>
                <value><call bean="jetty.resourceHandler"/></value>
                <value><call bean="jetty.defaultHandler"/></value>
                <value><call bean="jetty.requestLog"/></value>
            </item>
        </properties>
    </bean>

    <bean id="jetty.contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection" scope="prototype">
        <properties>
            <item name="handlers" type="array">
                <value><call bean="jetty.contexts.root"/></value>
            </item>
        </properties>
    </bean>

    <bean id="jetty.contexts.root" class="com.aspectran.with.jetty.JettyWebAppContext" scope="prototype">
        <properties>
            <item name="contextPath" value="/"/>
            <item name="war" value="#{basePath}/webapps/root"/>
            <item name="persistTempDirectory" value="true" valueType="boolean"/>
        </properties>
    </bean>

    <bean id="jetty.resourceHandler" class="org.eclipse.jetty.server.handler.ResourceHandler" scope="prototype"/>

    <bean id="jetty.defaultHandler" class="org.eclipse.jetty.server.handler.DefaultHandler" scope="prototype"/>

    <bean id="jetty.requestLog" class="org.eclipse.jetty.server.handler.RequestLogHandler" scope="prototype">
        <properties>
            <item name="requestLog">#{jetty.ncsaRequestLog}</item>
        </properties>
    </bean>

    <bean id="jetty.ncsaRequestLog" class="org.eclipse.jetty.server.NCSARequestLog" scope="prototype">
        <properties>
            <item name="filename">#{basePath}/logs/jetty-yyyy_mm_dd.request.log</item>
            <item name="filenameDateFormat">yyyy_MM_dd</item>
            <item name="logDateFormat">yyyy-MM-dd HH:mm:ss Z</item>
            <item name="logTimeZone">GMT+9</item>
            <item name="retainDays" valueType="int">90</item>
            <item name="append" valueType="boolean">true</item>
            <item name="logLatency" valueType="boolean">true</item>
        </properties>
    </bean>

</aspectran>

=== fermadeiral/bears-benchmark/demo/app/config/aspectran/web/web-config.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        An Aspectran configuration for Web Application Service.
        Note that the name of the Translet corresponding to the request URI always starts with a forward slash (/).
    </description>

    <bean id="jspViewDispatcher" class="com.aspectran.web.support.view.JspViewDispatcher">
        <description>
            Register a JSP View Dispatcher.
        </description>
        <properties>
            <item name="prefix">/WEB-INF/jsp/</item>
            <item name="suffix">.jsp</item>
        </properties>
    </bean>

    <aspect id="transletSettings">
        <description>
            Specifies the environment variables used during request and response processing.
        </description>
        <joinpoint target="translet"/>
        <settings>
            <setting name="characterEncoding" value="utf-8"/>
            <setting name="contentEncoding" value="gzip"/>
            <setting name="viewDispatcher" value="jspViewDispatcher"/>
            <setting name="indentString" value="  "/>
        </settings>
    </aspect>

    <append file="/config/aspectran/web/translets/main.xml"/>
    <append file="/config/aspectran/web/translets/hello-world.xml"/>
    <append file="/config/aspectran/web/translets/gs-rest-service.xml"/>
    <append file="/config/aspectran/web/translets/file-upload.xml"/>
    <append file="/config/aspectran/web/terminal/translet-interpreter.xml"/>

</aspectran>

=== fermadeiral/bears-benchmark/with-jetty/src/test/resources/config/aspectran/jetty-controller.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        A collection of commands for controlling the Jetty Server.
    </description>

    <translet name="jetty">
        <description style="apon">
            |
            |{{underline}}To control Jetty, try one of the following commands:{{off}}
            |   {{CYAN}}jetty start{{fg:off}}  Runs a Jetty Server
            |   {{CYAN}}jetty stop{{fg:off}}   Stops the currently running Jetty Server
        </description>
        <transform type="transform/text">
            <template style="apon">
                |
                |   {{YELLOW}}Jetty #{jetty.server^version} - #{jetty.server^state}{{off}}
                |
            </template>
        </transform>
    </translet>

    <translet name="jetty start">
        <description style="apon">
            |
            |   {{WHITE}}Starting the Jetty Server...{{off}}
            |-----------------------------------------
        </description>
        <action bean="jetty.server" method="start"/>
        <transform type="transform/text">
            <template style="apon">
                |
                |   {{YELLOW}}Jetty #{jetty.server^version} - #{jetty.server^state}{{off}}
                |   Web server started on localhost:%{jetty.server.port}
                |
            </template>
        </transform>
        <exception>
            <thrown type="java.net.BindException">
                <transform type="transform/text">
                    <template style="apon">
                        |
                        |   {{RED}}Jetty Server Error - Port %{jetty.server.port} already in use{{off}}
                        |
                    </template>
                </transform>
            </thrown>
        </exception>
    </translet>

    <translet name="jetty stop">
        <description style="apon">
            |
            |   {{WHITE}}Stopping the Jetty Server...{{off}}
            |-----------------------------------------
        </description>
        <action bean="jetty.server" method="stop"/>
        <transform type="transform/text">
            <template style="apon">
                |
                |   {{YELLOW}}Jetty #{jetty.server^version} - #{jetty.server^state}{{off}}
                |
            </template>
        </transform>
    </translet>

</aspectran>

=== fermadeiral/bears-benchmark/core/src/test/resources/config/sample/scheduler-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <settings>
        <setting name="transletNamePattern" value="*.job"/>
    </settings>

    <bean id="defaultScheduler1" class="com.aspectran.scheduler.support.QuartzSchedulerFactoryBean">
        <properties>
            <item type="properties" name="quartzProperties">
                <value name="org.quartz.scheduler.instanceName">AspectranQuartzScheduler-1</value>
                <value name="org.quartz.scheduler.rmi.export">false</value>
                <value name="org.quartz.scheduler.rmi.proxy">false</value>
                <value name="org.quartz.scheduler.wrapJobExecutionInUserTransaction">false</value>
                <value name="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</value>
                <value name="org.quartz.threadPool.threadCount">10</value>
                <value name="org.quartz.threadPool.threadPriority">5</value>
                <value name="org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread">true</value>
                <value name="org.quartz.jobStore.misfireThreshold">60001</value>
                <value name="org.quartz.jobStore.class">org.quartz.simpl.RAMJobStore</value>
            </item>
        </properties>
    </bean>

    <bean id="schedulerFactory" class="org.quartz.impl.StdSchedulerFactory">
        <constructor>
            <arguments>
                <item type="properties">
                    <value name="org.quartz.scheduler.instanceName">AspectranQuartzScheduler-2</value>
                    <value name="org.quartz.scheduler.rmi.export">false</value>
                    <value name="org.quartz.scheduler.rmi.proxy">false</value>
                    <value name="org.quartz.scheduler.wrapJobExecutionInUserTransaction">false</value>
                    <value name="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</value>
                    <value name="org.quartz.threadPool.threadCount">10</value>
                    <value name="org.quartz.threadPool.threadPriority">5</value>
                    <value name="org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread">true</value>
                    <value name="org.quartz.jobStore.misfireThreshold">60000</value>
                    <value name="org.quartz.jobStore.class">org.quartz.simpl.RAMJobStore</value>
                </item>
            </arguments>
        </constructor>
    </bean>

    <bean id="defaultScheduler2" factoryBean="schedulerFactory" factoryMethod="getScheduler"/>

    <schedule id="scheduler1">
        <scheduler bean="defaultScheduler1">
            <trigger type="simple">
                intervalInSeconds: 3
                repeatCount: 10
            </trigger>
        </scheduler>
        <job translet="job1"/>
    </schedule>

    <schedule id="scheduler2">
        <scheduler bean="defaultScheduler2">
            <trigger type="simple">
                startDelaySeconds: 2
                intervalInSeconds: 1
                repeatCount: 10
            </trigger>
        </scheduler>
        <job translet="job2"/>
    </schedule>

    <bean id="scheduleAction" class="com.aspectran.core.sample.schedule.ScheduleAction"/>

    <translet name="job1">
        <action bean="scheduleAction" method="delay">
            <arguments>
                <item valueType="long">1</item>
            </arguments>
        </action>
        <transform type="transform/text" contentType="text/plain">
            <template>(1) Hello, World!</template>
        </transform>
    </translet>

    <translet name="job2">
        <action bean="scheduleAction" method="delay">
            <arguments>
                <item valueType="long">2</item>
            </arguments>
        </action>
        <transform type="transform/text" contentType="text/plain">
            <template>(2) Hello, World!</template>
        </transform>
    </translet>

</aspectran>

=== fermadeiral/bears-benchmark/demo/app/config/aspectran/root-config.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">
<aspectran>

    <description style="apon">
        |
        |{{bold}}Commands that can run examples:{{bold:off}}
        |   {{CYAN}}hello{{fg:off}}      Prints "Hello, World!" in your console
        |   {{CYAN}}hello2{{fg:off}}     Prints "Hello, World!" in your console using ANSI escape sequences
        |   {{CYAN}}echo{{fg:off}}       It accepts parameters and print as is
        |   {{CYAN}}echo2{{fg:off}}      It accepts parameters and attributes, and print them as is
        |   {{CYAN}}login{{fg:off}}      It accepts parameters required for login and prints them
        |   {{CYAN}}chpw{{fg:off}}       It accepts parameters required for changing password and prints them
        |   {{CYAN}}speak{{fg:off}}      Converts any written text into spoken words
        |
        |{{bold}}To control Jetty, try one of the following commands:{{bold:off}}
        |   {{MAGENTA}}jetty{{fg:off}}        Displays commands required to control Jetty server
        |   {{MAGENTA}}jetty start{{fg:off}}  Runs a Jetty server
        |   {{MAGENTA}}jetty stop{{fg:off}}   Stops the currently running Jetty server
        |
        |{{bold}}Once a Jetty server is running, point your web browser to:{{bold:off}}
        |   {{81}}http://localhost:8088/{{fg:off}}
        |
    </description>

    <bean id="basePath" class="com.aspectran.core.support.BasePathFactoryBean"/>
    <bean id="currentTranslet" class="com.aspectran.core.support.CurrentTransletFactoryBean" scope="request"/>
    <bean id="currentActivityData" class="com.aspectran.core.support.CurrentActivityDataFactoryBean" scope="request"/>

    <aspect id="activityDataAccessibility">
        <description>
            The Activity Data Map of all translets can be referenced as a "data" attribute in View Dispatching.
        </description>
        <joinpoint target="translet"/>
        <advice>
            <before>
                <echo>
                    <attributes>
                        <item name="data">
                            <call bean="currentActivityData"/>
                        </item>
                    </attributes>
                </echo>
            </before>
        </advice>
    </aspect>

    <aspect id="errorReport">
        <description>
            Prints a simple error message to the console if an unexpected error occurs during processing of the Translet.
        </description>
        <joinpoint target="translet"/>
        <exception>
            <thrown>
                <transform type="transform/text">
                    <template style="apon">
                        |
                        |   {{RED}}An Error Occurred!{{off}}
                        |{{BLUE}}-----------------------------------------------------------------------------------------{{off}}
                        |   #{currentTranslet^rootCauseOfRaisedException}
                        |
                    </template>
                </transform>
            </thrown>
        </exception>
    </aspect>

    <append file="/config/aspectran/jetty/jetty-config.xml"/>
    <append file="/config/aspectran/shell/shell-config.xml"/>
    <append file="/config/aspectran/web/web-config.xml"/>

</aspectran>

=== fermadeiral/bears-benchmark/demo/app/config/aspectran/web/translets/hello-world.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <translet name="/examples/hello-world">
        <dispatch name="templates/default">
            <echo id="page">
                <attributes>
                    <item name="headline">Hello, World!</item>
                    <item name="teaser">This is the output of a JSP page that is part of the HelloWorld application.</item>
                    <item name="include">pages/hello-world</item>
                </attributes>
            </echo>
        </dispatch>
    </translet>

</aspectran>

=== fermadeiral/bears-benchmark/with-jetty/src/test/resources/config/aspectran/root-config.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">
<aspectran>

    <bean id="basePath" class="com.aspectran.core.support.BasePathFactoryBean"/>
    <bean id="currentTranslet" class="com.aspectran.core.support.CurrentTransletFactoryBean" scope="request"/>
    <bean id="currentActivityData" class="com.aspectran.core.support.CurrentActivityDataFactoryBean" scope="request"/>

    <aspect id="activityDataAccessibility">
        <description>
            The Activity Data Map of all translets can be referenced as a "data" attribute in View Dispatching.
        </description>
        <joinpoint target="translet"/>
        <advice>
            <before>
                <echo>
                    <attributes>
                        <item name="data">
                            <call bean="currentActivityData"/>
                        </item>
                    </attributes>
                </echo>
            </before>
        </advice>
    </aspect>

    <aspect id="errorReport">
        <description>
            Prints a simple error message to the console if an unexpected error occurs during processing of the Translet.
        </description>
        <joinpoint target="translet"/>
        <exception>
            <thrown>
                <transform type="transform/text">
                    <template style="apon">
                        |
                        |   {{RED}}An Error Occurred!{{off}}
                        |{{BLUE}}-----------------------------------------------------------------------------------------{{off}}
                        |   #{currentTranslet^rootCauseOfRaisedException}
                        |
                    </template>
                </transform>
            </thrown>
        </exception>
    </aspect>

    <bean id="jspViewDispatcher" class="com.aspectran.web.support.view.JspViewDispatcher">
        <description>
            Register a JSP View Dispatcher.
        </description>
        <properties>
            <item name="prefix">/WEB-INF/jsp/</item>
            <item name="suffix">.jsp</item>
        </properties>
    </bean>

    <aspect id="transletSettings">
        <description>
            Specifies the environment variables used during request and response processing.
        </description>
        <joinpoint target="translet"/>
        <settings>
            <setting name="characterEncoding" value="utf-8"/>
            <setting name="contentEncoding" value="gzip"/>
            <setting name="viewDispatcher" value="jspViewDispatcher"/>
            <setting name="indentString" value="  "/>
        </settings>
    </aspect>

    <append resource="config/aspectran/jetty-config.xml"/>
    <append resource="config/aspectran/jetty-controller.xml"/>

    <translet name="/hello">
        <transform type="transform/text">
            <template style="apon">
                |world
            </template>
        </transform>
    </translet>

    <translet name="/hello_jsp">
        <dispatch name="hello"/>
    </translet>

</aspectran>
