=== fermadeiral/bears-benchmark/core/src/main/resources/com/aspectran/core/context/rule/parser/xml/dtd/aspectran-5.dtd
<?xml version="1.0" encoding="utf-8"?>

<!--
  XML DTD for the Aspectran Configuration File, Version 5.0

  Copyright 2008-2017 The Aspectran Project

  This DTD module is identified by the PUBLIC and SYSTEM identifiers:

  PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
  SYSTEM "http://aspectran.github.io/dtd/aspectran-5.dtd">

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                             "http://aspectran.github.io/dtd/aspectran-5.dtd">
-->

<!ELEMENT aspectran (
  description?,
  (settings? | environment* | typeAliases* | aspect* | bean* | template* | schedule* | translet* | append*)*
)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  style   (apon | compact | compressed) #IMPLIED
>

<!ELEMENT settings (#PCDATA | setting)*>
<!ELEMENT setting (#PCDATA)>
<!ATTLIST setting
  name    CDATA #REQUIRED
  value   CDATA #IMPLIED
>

<!ELEMENT environment (#PCDATA | properties)*>
<!ATTLIST environment
  profile CDATA #IMPLIED
>

<!ELEMENT typeAliases (typeAlias*)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
  alias   CDATA #REQUIRED
  type    CDATA #REQUIRED
>

<!ELEMENT append EMPTY>
<!ATTLIST append
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  format   (xml | apon) #IMPLIED
  profile  CDATA #IMPLIED
>

<!ELEMENT aspect (description?, joinpoint?, settings?, advice?, exception?)>
<!ATTLIST aspect
  id       ID #IMPLIED
  order    CDATA #IMPLIED
  isolated (true | false) #IMPLIED
>

<!ELEMENT joinpoint (#PCDATA)>
<!ATTLIST joinpoint
  target  (session | translet | method) #IMPLIED
>

<!ELEMENT advice (before?, after?, around?, finally?)>
<!ATTLIST advice
  bean    CDATA #IMPLIED
>

<!ELEMENT before  (headers | echo | action)>
<!ELEMENT after   (headers | echo | action)>
<!ELEMENT around  (action)>
<!ELEMENT finally (thrown?, (headers | echo | action))>

<!ELEMENT exception (description?, thrown*)>

<!ELEMENT thrown ((headers | echo | action)? | transform? | dispatch? | redirect? | forward?)*>
<!ATTLIST thrown
  type    CDATA #IMPLIED
>

<!ELEMENT bean (description?, filter?, constructor?, properties?)>
<!ATTLIST bean
  id            CDATA #IMPLIED
  class         CDATA #IMPLIED
  scan          CDATA #IMPLIED
  mask          CDATA #IMPLIED
  factoryBean   CDATA #IMPLIED
  factoryMethod CDATA #IMPLIED
  initMethod    CDATA #IMPLIED
  destroyMethod CDATA #IMPLIED
  scope         (singleton | prototype | request | session | application) #IMPLIED
  singleton     (true | false) #IMPLIED
  lazyInit      (true | false) #IMPLIED
  important     (true | false) #IMPLIED
>

<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
  class   CDATA #IMPLIED
>

<!ELEMENT constructor (arguments?)>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template
  id       CDATA #IMPLIED
  engine   CDATA #IMPLIED
  style    (apon | compact | compressed) #IMPLIED
  name     CDATA #IMPLIED
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  encoding CDATA #IMPLIED
  noCache  (true | false) #IMPLIED
>

<!ELEMENT schedule (description?, scheduler, job*)>
<!ATTLIST schedule
  id      ID #IMPLIED
>

<!ELEMENT scheduler (trigger)>
<!ATTLIST scheduler
  bean    CDATA #IMPLIED
>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
  type    CDATA #IMPLIED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
  translet CDATA #REQUIRED
  method   CDATA #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT translet (
  (description?, request?, content*, contents?, response*, exception?) |
  (description?, request?, content*, contents?, (transform | dispatch | redirect | forward)?, exception?) |
  (description?, request?, (action? | include? | echo? | headers?)*, response*, exception?) |
  (description?, request?, (action? | include? | echo? | headers?)*, (transform | dispatch | redirect | forward)?, exception?) |
  (description?, parameters?, attributes?, (action? | include? | echo? | headers?)*, (transform | dispatch | redirect | forward)?, exception?)
)>
<!ATTLIST translet
  name    CDATA #REQUIRED
  scan    CDATA #IMPLIED
  mask    CDATA #IMPLIED
  method  CDATA #IMPLIED
>

<!ELEMENT request (parameters?, attributes?)>
<!ATTLIST request
  method   CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT contents (content*)>
<!ATTLIST contents
  name      CDATA #IMPLIED
  omittable (true | false) #IMPLIED
>

<!ELEMENT content (action? | include? | echo? | headers?)*>
<!ATTLIST content
  name      CDATA #IMPLIED
  omittable (true | false) #IMPLIED
  hidden    (true | false) #IMPLIED
>

<!ELEMENT action (arguments?, properties?)>
<!ATTLIST action
  id      CDATA #IMPLIED
  bean    CDATA #IMPLIED
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT include (parameters?, attributes?)>
<!ATTLIST include
  id       CDATA #IMPLIED
  translet CDATA #REQUIRED
  hidden   (true | false) #IMPLIED
>

<!ELEMENT echo (#PCDATA | attributes | item)*>
<!ATTLIST echo
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT headers (#PCDATA | item)*>
<!ATTLIST headers
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT response (transform? | dispatch? | redirect? | forward?)>
<!ATTLIST response
  name     CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT transform ((action? | include? | echo? | headers?)*, (template? | call?))>
<!ATTLIST transform
  type        CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
  pretty      (true | false) #IMPLIED
>

<!ELEMENT dispatch (action? | include? | echo? | headers?)*>
<!ATTLIST dispatch
  name        CDATA #REQUIRED
  dispatcher  CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT redirect ((action? | include? | echo? | headers?)*, parameters*)>
<!ATTLIST redirect
  contentType           CDATA #IMPLIED
  path                  CDATA #REQUIRED
  encoding              CDATA #IMPLIED
  excludeNullParameter  (true | false) #IMPLIED
  excludeEmptyParameter (true | false) #IMPLIED
  default               (true | false) #IMPLIED
>

<!ELEMENT forward ((action? | include? | echo? | headers?)*, attributes?)>
<!ATTLIST forward
  contentType CDATA #IMPLIED
  translet    CDATA #REQUIRED
  default     (true | false) #IMPLIED
>

<!ELEMENT parameters (#PCDATA | item)*>
<!ELEMENT attributes (#PCDATA | item)*>
<!ELEMENT properties (#PCDATA | item)*>
<!ELEMENT arguments  (#PCDATA | item)*>

<!ELEMENT item (#PCDATA | value | call | null)*>
<!ATTLIST item
  type         (single | array | list | map | set | properties) #IMPLIED
  name         CDATA #IMPLIED
  value        CDATA #IMPLIED
  valueType    (string | int | long | float | double | boolean | parameters | file | multipartFile) #IMPLIED
  defaultValue CDATA #IMPLIED
  tokenize     (true | false) #IMPLIED
  mandatory    (true | false) #IMPLIED
  security     (true | false) #IMPLIED
>

<!ELEMENT value (#PCDATA | call | null)*>
<!ATTLIST value
  name     CDATA #IMPLIED
  tokenize (true | false) #IMPLIED
>

<!ELEMENT call EMPTY>
<!ATTLIST call
  bean      CDATA #IMPLIED
  template  CDATA #IMPLIED
  parameter CDATA #IMPLIED
  attribute CDATA #IMPLIED
  property  CDATA #IMPLIED
>

<!ELEMENT null EMPTY>

=== fermadeiral/bears-benchmark/demo/app/config/aspectran/web/translets/main.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        A collection of Translets for the main page.
    </description>

    <translet name="/">
        <dispatch name="templates/default">
            <echo id="page">
                <attributes>
                    <item name="headline">Welcome to Aspectran Demo</item>
                    <item name="teaser">The "Aspectran Demo" is a reference application created to show how to develop Aspectran applications following the recommended best practices.</item>
                    <item name="include">pages/main</item>
                </attributes>
            </echo>
        </dispatch>
    </translet>

</aspectran>

=== fermadeiral/bears-benchmark/embed/src/test/resources/config/embedded/embedded-test-config.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        Aspectran configuration for embedded mode for tests
    </description>

    <bean id="basePath" class="com.aspectran.core.support.BasePathFactoryBean"/>
    <bean id="currentTranslet" class="com.aspectran.core.support.CurrentTransletFactoryBean" scope="request"/>
    <bean id="currentActivityData" class="com.aspectran.core.support.CurrentActivityDataFactoryBean" scope="request"/>

    <bean scan="com.aspectran.embed.service.**.*Bean" mask="com.aspectran.embed.service.**"/>

    <bean scan="com.aspectran.embed.service.**.*Configuration" mask="com.aspectran.embed.service.**"/>

    <bean scan="com.aspectran.embed.service.**.*Action" mask="com.aspectran.embed.service.**"/>

    <bean id="freemarkerConfigurationFactory" class="com.aspectran.core.support.freemarker.FreeMarkerConfigurationFactoryBean">
        <properties>
            <item name="freemarkerSettings" type="properties">
                <value name="incompatible_improvements">2.3.23</value>
                <value name="template_exception_handler">rethrow</value>
                <value name="default_encoding">UTF-8</value>
                <value name="number_format">0.####</value>
            </item>
            <item name="trimDirectives" valueType="parameters">
                directive: {
                    name: trim
                }
                directive: {
                    name: where
                    prefix: "WHERE "
                    deprefixes: [
                        "and "
                        "and\t"
                        "or "
                        "or\t"
                    ]
                }
                directive: {
                    name: set
                    prefix: "SET "
                    desuffixes: ","
                }
            </item>
        </properties>
    </bean>

    <bean id="freemarker" class="com.aspectran.core.support.freemarker.FreeMarkerTemplateEngine">
        <constructor>
            <arguments>
                <item><call bean="freemarkerConfigurationFactory"/></item>
            </arguments>
        </constructor>
    </bean>

    <aspect id="transletSettings">
        <description>
            Specifies the environment variables used during request and response processing.
        </description>
        <joinpoint target="translet"/>
        <advice>
            <before>
                <echo>
                    <attributes>
                        <item name="data">
                            <call bean="currentActivityData"/>
                        </item>
                    </attributes>
                </echo>
            </before>
        </advice>
    </aspect>

    <translet name="echo123">
        <parameters>
            <item name="input-1">1</item>
            <item name="input-2">2</item>
            <item name="input-3">3</item>
        </parameters>
        <transform type="transform/text" contentType="text/plain">
            <template engine="token" style="apon">
                |------------------------------------------------
                |${input-1}${input-2}${input-3}
                |@{data^input-1}@{data^input-2}@{data^input-3}
                |------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="echo">
        <request>
            <parameters>
                <item name="input-1">${input-1:12345}</item>
                <item name="input-2">${input-2:67890}</item>
            </parameters>
        </request>
        <transform type="transform/text" contentType="text/plain">
            <template style="apon">
                |-------------------------------------
                |Using Builtin Token Template Engine
                |-------------------------------------
                |input-1: ${input-1}
                |input-2: ${input-2}
                |-------------------------------------
            </template>
        </transform>
    </translet>

    <template id="echo" engine="token" style="apon">
        |
        |ID: ${id}
        |Name: ${name}
        |Email: ${email}
        |
    </template>

    <template id="selectQuery" engine="freemarker">
        <![CDATA[
        SELECT
            '${name}' as name,
            '${email}' as email
        FROM table1
        <@directive.where>
            <#if id?has_content>
            AND id = :id
            </#if>
            <#if name?has_content>
            AND name = :name
            </#if>
            <#if email?has_content>
            AND email = :email
            </#if>
        </@directive.where>
        ORDER BY name
        ]]>
    </template>

    <template id="updateQuery" engine="freemarker">
        <![CDATA[
        UPDATE table1
        <@directive.set>
            <#if name??>
            name = :name,
            </#if>
            <#if email??>
            email = :email,
            </#if>
            <#if id??>
            id = :id,
            </#if>
        </@directive.set>
        WHERE id = :id
        ]]>
    </template>

    <translet name="include-test">
        <transform type="transform/text" contentType="text/plain">
            <include id="inc" translet="include-target">
                <attributes>
                    <item name="attr-1" value="1"/>
                    <item name="attr-2" value="2"/>
                    <item name="attr-3" value="3"/>
                </attributes>
            </include>
            <action id="action1" bean="SecondBean" method="getMessage"/>
            <template> :: @{action1}</template>
        </transform>
    </translet>

    <translet name="include-target">
        <transform type="transform/text" contentType="text/plain">
            <template>abc@{attr-1}@{attr-2}@{attr-3}</template>
        </transform>
    </translet>

    <translet name="attr-test">
        <request>
            <attributes>
                <item name="attr-1" value="1"/>
                <item name="attr-2" value="2"/>
                <item name="attr-3" value="3"/>
            </attributes>
        </request>
        <transform type="transform/text" contentType="text/plain">
            <template>abc@{attr-1}@{attr-2}@{attr-3}</template>
        </transform>
    </translet>

    <translet name="add-up">
        <action id="result" bean="action.TestAction" method="addUp">
            <arguments>
                <item value="1" valueType="int"/>
                <item value="2" valueType="int"/>
                <item value="3" valueType="int"/>
                <item valueType="int">#{action.TestAction^arg4}</item>
            </arguments>
        </action>
    </translet>

</aspectran>

=== fermadeiral/bears-benchmark/shell-jline/src/test/resources/config/shell/jline/freemarker-translets.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description>
        This is an example using the Freemarker template engine.
    </description>

    <bean id="freemarkerConfigurationFactory" class="com.aspectran.core.support.freemarker.FreeMarkerConfigurationFactoryBean">
        <properties>
            <item name="freemarkerSettings" type="properties">
                <value name="incompatible_improvements">2.3.23</value>
                <value name="template_exception_handler">rethrow</value>
                <value name="default_encoding">UTF-8</value>
                <value name="number_format">0.####</value>
            </item>
            <item name="trimDirectives" valueType="parameters">
                directive: {
                    name: trim
                }
                directive: {
                    name: where
                    prefix: "WHERE "
                    deprefixes: [
                        "and "
                        "and\t"
                        "or "
                        "or\t"
                    ]
                }
                directive: {
                    name: set
                    prefix: "SET "
                    desuffixes: ","
                }
            </item>
        </properties>
    </bean>

    <bean id="freemarker" class="com.aspectran.core.support.freemarker.FreeMarkerTemplateEngine">
        <constructor>
            <arguments>
                <item><call bean="freemarkerConfigurationFactory"/></item>
            </arguments>
        </constructor>
    </bean>

    <translet name="free">
        <description style="apon">
            |
            |   It uses the Freemarker template engine to output the values of the input parameters to the console.
            |
        </description>
        <request>
            <parameters>
                <item name="input_1">${input_1:12345}</item>
                <item name="input_2">${input_2:67890}</item>
            </parameters>
        </request>
        <transform type="transform/text">
            <template engine="freemarker" style="apon">
                |-------------------------------------
                |The input parameters are as follows:
                |-------------------------------------
                |input_1: ${input_1}
                |input_2: ${input_2}
                |-------------------------------------
                |Templated by Freemarker engine
                |-------------------------------------
            </template>
        </transform>
    </translet>

    <template id="selectOne" engine="freemarker" style="apon">
        <![CDATA[
        |--------------------------------------------------------
        |SELECT
        |    id,
        |    name,
        |    email
        |FROM users
        |<@directive.where>
        |    <#if id?has_content>
        |    id = :id
        |    </#if>
        |    <#if name?has_content>
        |    AND name = :name
        |    </#if>
        |    <#if email?has_content>
        |    AND email LIKE :email||'%'
        |    </#if>
        |</@directive.where>
        |ORDER BY name
        |--------------------------------------------------------
        | The values to be set in the PreparedStatement instance.
        | id    = ${id?default("")}
        | name  = ${name?default("")}
        | email = ${email?default("")}
        |--------------------------------------------------------
        ]]>
    </template>

    <template id="updateOne" engine="freemarker" style="apon">
        <![CDATA[
        |--------------------------------------------------------
        |UPDATE users
        |<@directive.set>
        |    name = :name,
        |    email = :email,
        |</@directive.set>
        |<@directive.where>
        |    id = :id
        |</@directive.where>
        |--------------------------------------------------------
        | The values to be set in the PreparedStatement instance.
        | id    = ${id?default("")}
        | name  = ${name?default("")}
        | email = ${email?default("")}
        |--------------------------------------------------------
        ]]>
    </template>

    <translet name="select">
        <description style="apon">
            |
            |   This example generates a simple SQL SELECT statement using the Freemarker template engine.
            |
        </description>
        <request>
            <parameters>
                <item name="id"/>
                <item name="name"/>
                <item name="email"/>
            </parameters>
        </request>
        <transform type="transform/text">
        	<call template="selectOne"/>
        </transform>
    </translet>

    <translet name="update">
        <description style="apon">
            |
            |   This example generates a simple SQL UPDATE statement using the Freemarker template engine.
            |
        </description>
        <request>
            <parameters>
                <item name="id" mandatory="true"/>
                <item name="name" mandatory="true">${name:Jane}</item>
                <item name="email" mandatory="true">${email:jane@mail.com}</item>
            </parameters>
        </request>
        <transform type="transform/text">
        	<call template="updateOne"/>
        </transform>
    </translet>

</aspectran>

=== fermadeiral/bears-benchmark/shell-jline/src/test/resources/config/shell/jline/shell-test-root-config.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 5.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-5.dtd">

<aspectran>

    <description style="apon">
        |Commands that can run the examples:
        |   hello     Runs the helloWorld() method of the sampleAction bean and prints the returned value to the console.
        |   echo      It accepts parameters and print them to the console.
        |   login     It accepts parameters used for login and print them to the console.
        |   chpw      It accepts parameters for changing the password and print them to the console.
        |   free      It uses the Freemarker template engine to output the values of the input parameters to the console.
        |   select    This example generates a simple SQL SELECT statement using the Freemarker template engine.
        |   update    This example generates a simple SQL UPDATE statement using the Freemarker template engine.
        |
    </description>

    <bean id="sampleAction" class="com.aspectran.shell.sample.SampleAction">
        <description>
            Defines one sample action that contains the helloWorld method.
        </description>
    </bean>

    <bean id="sampleAdvice" class="com.aspectran.shell.sample.SampleAdvice">
        <description>
            Action Method 실행 전 후에 주입할 Advice Action Method를 가지고 있는
            singleton 스코프를 가지는 Bean을 정의합니다.
        </description>
    </bean>

    <aspect id="sampleAdviceAspect">
        <description>
            sampleAction Bean의 helloWorld 메쏘드를 실행하는 Translet이 발견되면,
            해당 Translet의 실행 전에는 sampleAdvice Bean의 welcome 메쏘드를 실행하고,
            해당 Translet의 실행 후에는 sampleAdvice Bean의 goodbye 메쏘드를 실행합니다.
        </description>
        <joinpoint target="translet">
            pointcut: {
                +: hello@sampleAction^helloWorld
            }
        </joinpoint>
        <advice bean="sampleAdvice">
            <before>
                <action method="welcome"/>
            </before>
            <after>
                <action method="goodbye"/>
            </after>
        </advice>
    </aspect>

    <translet name="hello">
        <description>
            sampleAction 빈에서 helloWorld 메쏘드를 실행합니다.
            helloWorld 메쏘드가 반환하는 "Hello, World." 문자열을 텍스트 형식의 컨텐츠로 응답합니다.
        </description>
        <transform type="transform/text">
            <action id="helloData" bean="sampleAction" method="helloWorld"/>
        </transform>
    </translet>

    <translet name="echo">
        <description style="apon">
            |
            |   It accepts parameters and print them to the console.
            |
        </description>
        <request>
            <parameters>
                <item name="input-1">${prefix} - 1</item>
                <item name="input-2">${prefix} - 2</item>
                <item name="input-3">${prefix} - 3</item>
            </parameters>
        </request>
        <transform type="transform/text" contentType="text/plain">
            <template engine="token" style="apon">
                |---------------------------------------------------
                |The parameters you entered are:
                |---------------------------------------------------
                |input-1: ${input-1}
                |input-2: ${input-2}
                |input-3: ${input-3}
                |---------------------------------------------------
                |Templated by Built-in engine
                |---------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="echo2">
        <description style="apon">
            |
            |   It accepts parameters and print them to the console.
            |
        </description>
        <request>
            <parameters>
                <item name="input-1">PARA ${input-1:12345}</item>
                <item name="input-2">PARA ${input-2:67890}</item>
                <item name="input-3">PARA ${input-3-1} and ${input-3-2}</item>
            </parameters>
            <attributes>
                <item name="input-4">ATTR ${input-4}</item>
            </attributes>
        </request>
        <transform type="transform/text" contentType="text/plain">
            <template engine="token" style="apon">
                |---------------------------------------------------
                |The input parameters and attributes are as follows:
                |---------------------------------------------------
                |input-1: ${input-1} - This is a parameter.
                |input-2: ${input-2} - This is a parameter.
                |input-3: ${input-3} - This is a parameter.
                |input-4: @{input-4} - This is an attribute.
                |---------------------------------------------------
                |Templated by Built-in engine
                |---------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="login">
        <description style="apon">
            |
            |   If you enter the required ID and password for login, it will be printed on the console.
            |
        </description>
        <request>
            <parameters>
                <item name="email">${emailId}@${emailDomain}</item>
                <item name="password" security="true"/>
            </parameters>
        </request>
        <transform type="transform/text">
            <template style="apon">
                |-----------------------------------------
                | You entered the following for login:
                |   email: ${email}
                |   password: ${password}
                |-----------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="chpw">
        <description style="apon">
            |
            | If you enter parameters to change the password, it will be printed on the console.
            |
        </description>
        <request>
            <parameters>
                <item name="email">${emailId}@${emailDomain}</item>
                <item name="password" security="true"/>
                <item name="confirmPassword" security="true"/>
            </parameters>
        </request>
        <transform type="transform/text">
            <template style="apon">
                |--------------------------------------------------------
                | You entered the following to change your password:
                |   email: ${email}
                |   password: ${password}
                |   confrim password: ${confirmPassword}
                |--------------------------------------------------------
            </template>
        </transform>
    </translet>

    <append resource="config/shell/jline/freemarker-translets.xml"/>

</aspectran>
